import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Main from './pages/prog_parse_tags/Main'
import App from './pages/_app'
import React from 'react'
import { ReactDOM } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
    </>
  )
}
