import Head from 'next/head'
import Main from './prog_parse_tags/Main'
import React from 'react'
import SectionImage from './prog_parse_tags/blog_for_image/SectionImage'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="dashboard-wrapper">
        <Main/>
        <SectionImage/>
      </div>
    </>
  )
}
