import Head from 'next/head'
import React from 'react'
import { ReactDOM } from 'react'
import ExamList from './prog_parse_tags/exam/Exam'



export default function Exam() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ExamList/>
    </>
  )
}